module.exports = {
  COMMENT_FETCH: 'COMMENT_FETCH',
  COMMENT_FETCH_SUCCESS: 'COMMENT_FETCH_SUCCESS',
  COMMENT_FETCH_FAILED: 'COMMENT_FETCH_FAILED',

  COMMENT_CREATE: 'COMMENT_CREATE',
  COMMENT_CREATE_SUCCESS: 'COMMENT_CREATE_SUCCESS',
  COMMENT_CREATE_FAILED: 'COMMENT_CREATE_FAILED',

  COMMENT_DELETE: 'COMMENT_DELETE',
  COMMENT_DELETE_SUCCESS: 'COMMENT_DELETE_SUCCESS',
  COMMENT_DELETE_FAILED: 'COMMENT_DELETE_FAILED',
};
