module.exports = {
  TASK_FETCH: 'TASK_FETCH',
  TASK_FETCH_SUCCESS: 'TASK_FETCH_SUCCESS',
  TASK_FETCH_FAILED: 'TASK_FETCH_FAILED',

  TASK_CREATE: 'TASK_CREATE',
  TASK_CREATE_SUCCESS: 'TASK_CREATE_SUCCESS',
  TASK_CREATE_FAILED: 'TASK_CREATE_FAILED',

  TASK_EDIT: 'TASK_EDIT',
  TASK_EDIT_SUCCESS: 'TASK_EDIT_SUCCESS',
  TASK_EDIT_FAILED: 'TASK_EDIT_FAILED',

  TASK_DELETE: 'TASK_DELETE',
  TASK_DELETE_SUCCESS: 'TASK_DELETE_SUCCESS',
  TASK_DELETE_FAILED: 'TASK_DELETE_FAILED',
};
