module.exports = {
  USER_SIGN_UP: 'USER_SIGN_UP',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILED: 'USER_SIGN_UP_FAILED',

  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_FAILED: 'USER_SIGN_IN_FAILED',

  USER_SIGN_OUT: 'USER_SIGN_OUT',
  USER_SIGN_OUT_SUCCESS: 'USER_SIGN_OUT_SUCCESS',
  USER_SIGN_OUT_FAILED: 'USER_SIGN_OUT_FAILED',
};
